name: mrx-link-demo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - nodejs=16
  - pip>=21
  - pip:
      - aiofiles>=0.8
      - aiohttp>=3.8
      - astor>=0.8
      - black>=19.3b0
      - cloudpickle>=1.6
      - colorama>=0.4
      - dill>=0.3
      - isort>=5.7
      - Jinja2>=3.0
      - jsondiff>=2.0.0
      - jupyter-server<=1.17.0
      - jupyterlab>=3.1,<3.3
      - kfp>=1.6
      - matplotlib>=2.0
      - nbdime>=3.1,<3.2
      - networkx>=2.5
      - numpy>=1.19
      - optuna>=2.9
      - pandas>=1.1
      - pexpect>=4.7
      - pycryptodome>=3.14
      - pydantic>=1.8.0
      - pywinpty<2.0; python_version=='3.6' and sys_platform=='win32'
      - PyYAML>=5.4
      - pyzmq>=17
      - requirements-parser>=0.2
      - sqlalchemy>=1.4
