name: mrx-link-demo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip>=21
  - pip:
      - catboost>=1.0
      - livelossplot>=0.5
      - mrx_link==0.10.1
      - pytorch-lightning>=1.6
      - scikit-learn>=1.0
      - seaborn>=0.11
      - torch>=1.9
